### ISSUE TITLE
B1 Feedback

### ISSUE THREAD

**Issue by yuliaUU** [stat545ubc-2021/functions-YFL-UBC#1]
Awesome work!

-  why top 10? maybe make the number flexible so that the user could specify it themselves
-  My suggestion to switch x and y axis ( you don't have to do it) , I think it makes the names of the categories easier to read
- I would fill the boxplots with color ( or remove color completely) 
- try to apply some theme to a plot, so it will look neat and tidy.
- I can see two tests only. Please correct me if I am wrong
-  please check the proper markdown formatting, in many instances the image and text after were not separated and appear on the same line
![image](https://user-images.githubusercontent.com/54612866/142453322-242fc8cb-f864-4ae3-827f-19a8ef0bdd50.png)

**Comment by YFL-UBC** [comment]
Hi Yulia, 

Just want to confirm that I used the following 3 functions across 2 tests:  expect_s3_class(), expect_identical(), and expect_error().

**Comment by yuliaUU** [comment]
let me check again!

**Comment by yuliaUU** [comment]
you are right,  I would then make 3 tests  out of those functionst. I corrected your mark too!
