### ISSUE TITLE
B2 feedback

### ISSUE THREAD

**Issue by yuliaUU** [stat545ubc-2021/functions-YFL-UBC#2]
Great work!

- package should be in its own github repo, not as a subfolder
- devtools::install_github("stat545ubc-2021/functions-YFL-UBC/boxquickplot/") should not be run in a README, just displayed
- passed check()
- passed test()
-  ~forgot to Clean up objects in tests scripts with rm()~

**Comment by YFL-UBC** [comment]
Hi yulia, can you confirm which objects should be cleaned up with rm()? Thanks

**Comment by yuliaUU** [comment]
Hi Eric, I realized that you added the `msk` object inside the testthat, so you are all ok!
